apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "testappjdl"
  annotations:
    github.com/project-slug: dexmach-backstage-demo/testappjdl
    backstage.io/kubernetes-id: "testappjdl"
    backstage.io/kubernetes-namespace: "testappjdl"
    backstage.io/kubernetes-cluster: aks-pe-poc-01
    backstage.io/techdocs-ref: dir:.
    azure.com/tag-selector: backstage-entity-id/testappjdl
    grafana/alert-label-selector: "service=grafana-test"
    grafana/tag-selector: "grafanatag"
    grafana/dashboard-selector: "(tags @> 'grafana-test' || tags @> 'grafana-test') && tags @> 'generated'"
    grafana/dashboard-selector: grafana-test
  links:
    - url: https://testappjdl.jandelaet.com
      title: Website
spec:
  type: service
  owner: group:cloud-native
  lifecycle: experimental
  dependsOn:
    - Resource:acrdmbackstagepoc
    - Resource:aks-pe-poc-01
    - Resource:jandelaet.com
