{{- with .Values.volumes }}
{{ range . }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    {{- range .accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .storageRequest }}
  storageClassName: {{ default "" (.storageClassName | quote) }}
  volumeMode: {{default "Filesystem" .volumeMode }}
  volumeName: {{ .name }}
{{- end }}
{{- end }}