{{- $applicationName := include "app.name" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $applicationName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ required "The type of service to create is required." .Values.service.type | quote }}
  ports:
    - port: {{ required "The port number is required." .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
